version: "3.8"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - ./.env

  mongo:
    image: mongo:5.0.11
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234